### ISSUE TITLE
БЭМ и именование классов

### ISSUE THREAD

**Issue by dariathehuman** [lozovaya-collab/PetCare-test#19]
Я вижу большой пробел в понимании БЭМ, нужно подтянуть этот момент. 

Я попробую объяснить суть проблемы, разобрав блок с попапом.

<img width="526" alt="Screenshot 2021-06-28 at 15 05 29" src="https://user-images.githubusercontent.com/60440906/123633775-4d29ba00-d822-11eb-9859-e97cb4e1ff83.png">

1. С названием блока все в порядке, определились с тем, что блок называется popup. 
2. Далее по идее должны быть элементы блока. Элементы блока по методологии пишутся так: popup__block (2 нижних подчеркивания). На скриншоте видно, что нет ни одного элемента. Я пыталась найти логику в названиях, сначала подумала, что это все модификаторы. Но опять же, здесь вообще не нужны модификаторы, плюс ко всему они используются иначе. 
3. Нужно избегать длинных названий классов вроде таких: popup_form_details_my-pet_buttons_choice_pet, поскольку это плохо поддерживается и трудно читается.

Как бы я разметила попап по БЭМ:

```
section.popup
p.popup__title
  button.popup__close
  form.popup__form
    fieldset.popup__form-choice
      input.popup__form-choice-input
      input.popup__form-choice-input
    fieldset.popup__form-fields
      input.popup__form-fields-input
      input.popup__form-fields-input
      input.popup__form-fields-input
      input.popup__form-fields-input
      input.popup__form-fields-input
  button.popup__send
```

Все, здесь прозрачная структура, названия классов читаемые.

В БЭМ также есть хорошее правило: не делать элемент элемента. Если очень хочется, то нужно создать блок. Например, здесь также можно было сделать отдельный блок для формы (в данном случае не требуется, но вдруг сайт расширится и она нам потребуется где-то еще), тогда структура выглядела бы так:

```
section.popup
  p.popup__title
  button.popup__close
  form.popup__form popup-form
    fieldset.popup-form__choice
      input.popup-form__choice-input
      input.popup-form__choice-input
    fieldset.popup-form__fields
      input.popup-form__fields-input
      input.popup-form__fields-input
      input.popup-form__fields-input
      input.popup-form__fields-input
      input.popup-form__fields-input
  button.popup__send
```

То есть здесь форма является и элементом блока popup, и отдельным блоком popup-form со своими элементами.

Нужно стараться давать максимально простые и понятные названия классов, чтобы разработчикам в команде не было потом мучительно поддерживать код.

Ремарка насчет popup__title: можно использовать и заголовки, но как мне кажется, p здесь отлично подходит, если в классе название title, это не всегда нас принуждает использовать теги h1-h6

**Comment by lozovaya-collab** [comment]
Спасибо большое за такое подробное объяснение!
