### ISSUE TITLE
Адаптив

### ISSUE THREAD

**Issue by dariathehuman** [lozovaya-collab/PetCare-test#30]
1. Маленький боковой паддинг для десктопного разрешения, нужно больше пространства делать

<img width="668" alt="Screenshot 2021-06-28 at 16 33 25" src="https://user-images.githubusercontent.com/60440906/123645063-a8fa4000-d82e-11eb-81fb-53bc385d435e.png">

2. А здесь наоборот сильно большой. 

<img width="625" alt="Screenshot 2021-06-28 at 16 34 44" src="https://user-images.githubusercontent.com/60440906/123645187-c7f8d200-d82e-11eb-8d41-e399412466c3.png">

3. На разрешении 768px – адаптив совсем плохой, а по статистике именно это разрешение самое популярное среди планшетов (более 52%)

<img width="639" alt="Screenshot 2021-06-28 at 16 35 51" src="https://user-images.githubusercontent.com/60440906/123645430-02fb0580-d82f-11eb-894a-e9fc8cc02e0f.png">

4. На мобильных надо делать резиновую верстку всегда. Дизайнеры всегда будут давать какое-то одно мобильное разрешение, верстальщику же надо продумать, как будет выглядеть верстка и на 320px и на 420px. Оставлять контейнер 280px для больших мобильных экранов не получится. 

<img width="360" alt="Screenshot 2021-06-28 at 16 37 52" src="https://user-images.githubusercontent.com/60440906/123646101-946a7780-d82f-11eb-8513-ca499c5e20bf.png">

5. В сафари поломалась верстка блока чуть-чуть

<img width="305" alt="Screenshot 2021-06-28 at 16 53 36" src="https://user-images.githubusercontent.com/60440906/123648258-7a319900-d831-11eb-9d31-8ee98eeb32ac.png">

6. Также в сафари сломалась верстка кнопок слайдера
![IMG_0784](https://user-images.githubusercontent.com/60440906/123648450-a0573900-d831-11eb-88c1-02fc78aef96c.jpg)

**Comment by lozovaya-collab** [comment]
Починить верстку, чтобы в сафари хорошо отображалось - так и не удалось
